CREATE TABLE LINK (URL VARCHAR(1024) NOT NULL, TITLE VARCHAR(1024) NOT NULL, PROJECT_ID VARCHAR(40) NOT NULL, PRIMARY KEY (URL, TITLE, PROJECT_ID));
CREATE TABLE PROJECT (ID VARCHAR(40) NOT NULL, CUSTOMER_NAME VARCHAR(255), CUSTOMER_URL VARCHAR(255), DESCRIPTION TEXT, INTERVAL_FROM DATE, INTERVAL_TO DATE, TITLE VARCHAR(1024), PRIMARY KEY (ID));
ALTER TABLE IF EXISTS PROJECT ADD CONSTRAINT UNIQUE_TITLE_INTERVAL UNIQUE (TITLE, INTERVAL_FROM, INTERVAL_TO);
