matrix:
  include:
    - language: java
      jdk: oraclejdk9
      before_install:
        - cd geolud-server-java/
      script: mvn verify
    - language: node_js
      before_install:
        - cd geolud-client
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
        - npm run build
    - language: node_js
      before_install:
        - cd geolud-server-node
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
        - npm run build
