swagger: 2.0

info:
  title: Project API
  description: Project API description
  contact:
    name: Joe Developer
    email: joe@developers.kom
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: @project.version@

tags:
  - name: purpose
    description: scaffolding

host: server:8080
basePath: /api-path

paths:
  /projects:
    get:
      summary: All projects
      description: Returns all projects from the system.
      tags:
        - project
        - query
      parameters:
        - name: search
          in: query
          description: A search query for projects.
          type: string
      produces:
        - application/json
      responses:
        200:
          description: A list of projects.
          schema:
            type: array
            $ref: "#/definitions/Project"
        500:
          description: Projects are dead.

tsModels:
  - ../../model/ts/project.ts
