swagger: "2.0"
info:
  version: 1.4.1
  title: Swagger Geolud
  license:
    name: MIT
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /projects:
    get:
      summary: List all projects
      operationId: getProjects
      produces:
        - application/json
      tags:
        - project
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: An paged array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /projects/{projectId}:
    get:
      summary: Info for a specific project
      operationId: getProjectById
      produces:
        - application/json
      tags:
        - project
      parameters:
        - name: projectId
          in: path
          required: true
          description: The id of the project to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Project'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /contact:
    post:
      summary: Submit a new contact Request
      operationId: submitContactRequest
      consumes:
        - application/json
      tags:
        - contact
      parameters:
       - name: contactRequest
         in: body
         description: ContactRequest to submit
         required: true
         schema:
           $ref: '#/definitions/ContactRequest'
      responses:
       "200":
         description: OK
       default:
         description: unexpected error
         schema:
           $ref: '#/definitions/ErrorResponse'
definitions:
  Project:
    required:
      - id
      - name
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      period:
        type: string
      customer:
        $ref: '#/definitions/Customer'
      links:
        type: array
        items:
          $ref: '#/definitions/Link'
  Link:
    properties:
      title:
        type: string
      url:
        type: string
  ContactRequest:
    required:
      - email
      - message
    properties:
      name:
        type: string
      email:
        type: string
      message:
        type: string
  Customer:
    required:
      - name
    properties:
      name:
        type: string
      url:
        type: string
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string