/**
 * Swagger Icke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { Link } from './link';


export interface Project {
    id: string;
    title?: string;
    description?: string;
    period?: string;
    customer?: Customer;
    links?: Array<Link>;
}
