DROP TABLE IF EXISTS `link`;
DROP TABLE IF EXISTS `project`;
DROP TABLE IF EXISTS `flyway_schema_history`;
DROP TABLE IF EXISTS `LINK`;
DROP TABLE IF EXISTS `PROJECT`;
DROP TABLE IF EXISTS `FLYWAY_SCHEMA_HISTORY`;