CREATE TABLE LINK (PROJECT_ID VARCHAR(40) NOT NULL, TITLE VARCHAR(1024), URL VARCHAR(1024)) ENGINE=MYISAM;
CREATE TABLE PROJECT (ID VARCHAR(40) NOT NULL, CUSTOMER_NAME VARCHAR(255), CUSTOMER_URL VARCHAR(255), DESCRIPTION LONGTEXT, INTERVAL_FROM DATE, INTERVAL_TO DATE, TITLE VARCHAR(1024), PRIMARY KEY (ID)) ENGINE=MYISAM;
ALTER TABLE PROJECT ADD CONSTRAINT UNIQUE_TITLE_INTERVAL UNIQUE (TITLE, INTERVAL_FROM, INTERVAL_TO);
ALTER TABLE LINK ADD CONSTRAINT FK_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID);
