openapi: "3.0.0"
info:
  version: 1.4.1
  title: Swagger Petstore
  license:
    name: WTFPL
servers:
  - url: http://geolud.swagger.io/v1
paths:
  /projects:
    get:
      summary: List all projects
      operationId: getAllProjects
      tags:
        - projects
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a project
      operationId: createProject
      tags:
        - projects
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /projects/{projectId}:
    get:
      summary: Info for a specific project
      operationId: getProjectById
      tags:
        - projects
      parameters:
        - name: projectId
          in: path
          required: true
          description: The id of the project to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Project:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: uuid
        title:
          type: string
        description:
          type: string
        period:
          type: string
    Projects:
      type: array
      items:
        $ref: "#/components/schemas/Project"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string